# Generated by Django 6.1.1 on 2026-09-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='details_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ar',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
